repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: poetry run black .
      language: python
      types:
        -   python
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint 
      language: python
      types:
        -   python